// !bang background
// author: Fernando Iazeolla
// license: GPLv2


// This event is fired each time the user updates the text in the omnibox,
// as long as the extension's keyword mode is still active.
chrome.omnibox.onInputChanged.addListener(
  function(text, suggest) {
    console.log('inputChanged: ' + text);
    // suggest([
    //   {content: ">http://www.autistici.org/0xFE/!bang/", description: "goto !bang web site"},
    //   {content: ">http://www.autistici.org/0xFE/!bang/man.php", description: "goto !bang online documentation"}
    // ]);
});

//chrome.omnibox.onInputStarted.addListener(
//	function(){
//		console.log('inputStarted: ');
//    	//add web site sugestion
//	}
//);

// configuration ...
var searchsigil='!';
var defaultengine='g';
var gosigil='>';

// This event is fired with the user accepts the input in the omnibox.
chrome.omnibox.onInputEntered.addListener(
  function(text) {

  	var res=text.split(" ");
	// console.log(res)
  	var searchengine=("!" + res.shift());
	// console.log(searchengine)
  	if(searchengine.charAt(0)!=searchsigil) {res.unshift(searchengine);searchengine="null";}
  	var stringquery=res.join("%20");
  	//alert(searchengine+' '+stringquery);
    //console.log('search engine: ' + searchengine+ ' string query: '+stringquery);
    //alert('search engine: ' + searchengine+ ' string query: '+stringquery+take_searchengine(searchengine));
    //alert(make_queryURL(take_searchengine(searchengine),stringquery));
    var queryURL=make_queryURL(take_searchengine(searchengine),stringquery);
    //alert(queryURL);
    navigate(queryURL);
  });
function take_searchengine(ss){
	var ret=undefined;
	var localelang=window.navigator.language;
	var arr={
    "14": "https://14-tage-wettervorhersage.de/suche/?q=%s&lg=de",
    "1c": "https://1cak.com/search-0-%s",
    "3m": "http://www.trojmiasto.pl/s/%s/",
    "3t": "http://www.tritrans.net/cgibin/translate.cgi?spraak=Engelsk&Fra=%s&button=Translate%21",
    "42": "https://profile.intra.42.fr/searches/search?query=%s",
    "4": "https://www.4fitnessrules.com/workout-videos/?frm_search=%s",
    "47": "https://www.47news.jp/search?phrase=%s",
    "4g": "http://4chan.org/g/%s",
    "52": "http://food52.com/recipes/search?q=%s",
    "5e": "http://engl393-dnd5th.wikia.com/wiki/Special:Search?query=%s",
    "5": "http://fiverr.com/gigs/search?query=%s",
    "91": "http://www.91mobiles.com/topic/%s/all",
    "93": "https://hermetic.com/index?do=search&id=%s",
    "9": "http://9pp.co/search?q=%s",
    "9g": "http://9gag.com/search?query=%s",
    "a2": "http://alternativeto.net/browse/search/?q=%s&ignoreExactMatch=true",
    "a5": "https://v5.angular.io/api?query=%s",
    "a6": "https://v6.angular.io/api?query=%s",
    "a7": "https://v7.angular.io/api?query=%s",
    "aa": "http://www.amazon.com/s/&url=search-alias%3Dautomotive&field-keywords=%s",
    "a": "https://www.amazon.com/s/?tag=duc0c-20&url=search-alias%3Daps&field-keywords=%s",
    "ab": "http://airbitz.co/search?term=%s",
    "ac": "http://www.allocine.fr/recherche/?q=%s",
    "ad": "http://apple.stackexchange.com/search?q=%s",
    "ae": "https://www.aliexpress.com/wholesale?SearchText=%s",
    "af": "http://www.acronymfinder.com/%s.html",
    "ag": "http://www.android.gs/?s=&q=%s",
    "ah": "https://www.ah.nl/zoeken?rq=%s",
    "ai": "https://www.amazon.in/s/ref=nb_sb_noss?tag=duc21-21&url=search-alias%3Daps&field-keywords=%s ",
    "aj": "https://www.amazon.co.jp/s/?tag=duc0c-20&url=search-alias%3Daps&field-keywords=%s",
    "ak": "https://www.accountkiller.com/en/delete-%s-account",
    "al": "https://anilist.co/search/anime?search=%s",
    "am": "https://www.amazon.com/s/?tag=duc0c-20&url=search-alias%3Daps&field-keywords=%s",
    "an": "http://anilist.co/search?q=%s",
    "ao": "https://www.amazon.com/gp/your-account/order-history/ref=oh_aui_search?opt=ab&search=%s",
    "ap": "http://ap.org/Search/SearchResults?searchkeywords=%s",
    "ar": "http://allrecipes.com/search/default.aspx?qt=k&wt=%s&rt=r&origin=Recipe%20Search%20Results",
    "as": "http://smile.amazon.com/s?url=search-alias%3Daps&field-keywords=%s",
    "at": "http://www.addictivetips.com/archives/search/?cx=015974260755795457590%3Akigcmyffu6y&cof=FORID%3A11&ie=UTF-8&q=%s&s=Search",
    "au": "https://aur.archlinux.org/packages/?K=%s",
    "av": "https://www.avclub.com/search?q=%s",
    "aw": "https://wiki.archlinux.org/index.php?title=Special%3ASearch&search=%s",
    "ax": "http://androidxref.com/5.1.0_r1/search?&project=abi&project=art&project=bionic&project=bootable&project=build&project=cts&project=dalvik&project=developers&project=development&project=device&project=docs&project=external&project=frameworks&project=hardware&project=libcore&project=libnativehelper&project=ndk&project=packages&project=pdk&project=prebuilts&project=sdk&project=system&project=tools&q=%s",
    "\u00e4x": "https://www.levykauppax.fi/search/?q=%s",
    "ay": "https://www.aboutyou.de/suche?term=%s&search_source=ddgo",
    "az": "https://www.amazon.com/s/?tag=duc0c-20&url=search-alias%3Daps&field-keywords=%s",
    "b5": "http://babylon5.wikia.com/wiki/Special:Search?search=%s",
    "ba": "http://beeradvocate.com/search?q=%s&qt=beer",
    "bb": "https://bitbucket.org/repo/all/?name=%s",
    "b": "https://www.bing.com/search?q=%s",
    "bc": "http://blockchain.info/search/%s ",
    "bd": "http://www.baidu.com/s?wd=%s",
    "be": "https://blockexplorer.com/searchgo/%s",
    "bf": "http://www.buzzfeed.com/search?q=%s",
    "bg": "http://www.biblegateway.com/passage/?search=%s",
    "bh": "http://www.bhphotovideo.com/c/search?Ntt=%s",
    "bi": "https://www.bing.com/images/search?q=%s&go=&form=QBIL&qs=n",
    "bk": "https://www.bluekangaroo.com/products?term=%s",
    "bl": "http://explore.bl.uk/primo_library/libweb/action/search.do?fn=search&vl(freeText0)=%s",
    "bm": "https://www.bing.com/maps/?q=%s&obox=1",
    "bn": "http://www.barnesandnoble.com/s/%s",
    "bo": "http://www.boerse-online.de/suchergebnisse?_search=%s",
    "bp": "http://beautifulpixels.com/?s=%s ",
    "br": "http://www.baseball-reference.com/pl/player_search.cgi?search=%s",
    "bs": "https://www.bing.com/shop?q=%s",
    "bt": "https://www.bing.com/translator?text=%s",
    "bu": "https://bulbapedia.bulbagarden.net/w/index.php?title=Special%3ASearch&search=%s",
    "bv": "https://www.bing.com/videos?q=%s",
    "bw": "https://www.bing.com/weather/forecast?q=%s",
    "c2": "http://c2.com/cgi/fullSearch?search=%s",
    "c4": "http://www.channel4.com/search/?q=%s",
    "ca": "https://www.amazon.ca/s/?tag=duc22-20&field-keywords=%s",
    "cb": "https://www.crunchbase.com/textsearch?q=%s",
    "cc": "http://search.creativecommons.org/?q=%s",
    "c": "http://www.cnet.com/1770-5_1-0.html?query=%s",
    "cd": "http://www.collinsdictionary.com/dictionary/english/%s?showCookiePolicy=true",
    "ce": "http://forum.cheatengine.org/search.php?q=%s",
    "cg": "http://hub.culturegraph.org/search?query=%s",
    "ch": "http://chequeado.com/?s=%s",
    "ci": "https://www.codeigniter.com/user_guide/search.html?q=%s",
    "cj": "https://conjour.world/?s=%s",
    "ck": "http://www.chefkoch.de/rs/scr/s0/%s/Rezepte.html",
    "cl": "https://www.craigslist.org/search/sss?query=%s",
    "cm": "https://cm.center/catalog/?q=%s",
    "cn": "http://www.charitynavigator.org/index.cfm?bay=search.results&keyword_list=%s",
    "cp": "https://coinpaprika.com/?sort=%s",
    "cq": "http://qrzcq.com/call/%s",
    "cr": "http://codereview.stackexchange.com/search?q=%s",
    "cs": "http://www.cheapshark.com/search?q=%s",
    "ct": "http://www.canadiantire.ca/en/search-results.html?q=%s",
    "cu": "http://caniuse.com/#search=%s",
    "cv": "https://stats.stackexchange.com/search?q=%s",
    "cw": "https://www.codewars.com/kata/search/?q=%s",
    "cz": "https://complexityzoo.uwaterloo.ca/index.php?search=%s&title=Special%3ASearch",
    "d3": "https://dirty.ru/search/?query=%s",
    "da": "http://www.deviantart.com/browse/all/?section=&global=1&q=%s",
    "db": "https://m.douban.com/search/?query=%s",
    "dc": "https://duck.co/forum/search?q=%s",
    "dd": "https://devdocs.io/#q=%s",
    "d*": "https://www.joindiaspora.com/people?utf8=\u2713&q=%s",
    "de": "http://dict.tu-chemnitz.de/dings.cgi?query=%s",
    "df": "https://duckduckgo.com/?q=%s+site%3Adaringfireball.net",
    "dg": "http://www.desiringgod.org/search/results?utf8=%E2%9C%93&search_source=navbar&q=%s#gsc.tab=0&gsc.q={{{s}}}&gsc.page=1",
    "dh": "https://hub.docker.com/search/?q=%s&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0",
    "di": "http://www.dictionary.com/browse/%s",
    "dj": "https://docs.djangoproject.com/search/?q=%s",
    "dk": "https://store.docker.com/search?q=%s",
    "dl": "http://blog.desdelinux.net/?s=%s",
    "dm": "https://www.dailymotion.com/search/%s",
    "dn": "https://www.dn.se/sok/?q=%s&page=1&sort=relevance",
    "do": "https://www.digitalocean.com/community/search?q=%s",
    "dp": "http://www.duckduckgo.com/?q=site%3Adlang.org+%s",
    "dq": "http://dragon-quest.org/w/index.php?search=%s",
    "dr": "http://dribbble.com/search?q=%s",
    "ds": "http://www.standaard.be/zoeken?keyword=%s ",
    "dt": "https://deskthority.net/w/index.php?search=%s",
    "d": "http://www.thefreedictionary.com/%s",
    "?": "http://duckduckgo.com/?q=%s",
    "dv": "http://www.ikonet.com/fr/ledictionnairevisuel/static/qc/searchresults?cx=partner-pub-7156007925185226%3Atd1ipa-ejn8&cof=FORID%3A9&ie=UTF-8&q=%s&siteurl=www.ikonet.com%2Ffr%2Fledictionnairevisuel%2F&ref=www.ikonet.com%2Ffr%2Fledictionnairevisuel%2Fstatic%2Fqc%2Fsearchresults%3Fcx%3Dpartner-pub-7156007925185226%253Atd1ipa-ejn8%26cof%3DFORID%253A9%26ie%3DUTF-8%26q%3Dfraise%26siteurl%3Dwww.ikonet.com%252Ffr%252Fledictionnairevisuel%252Fstatic%252Fqc%252Fvisuel%26ref%3D%26ss%3D607j79921j6&ss=648j91840j6",
    "dx": "http://www.dx.com/s/%s",
    "dz": "https://www.deezer.com/search/%s",
    "e2": "http://everything2.com/title/%s?searchy=search",
    "eb": "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5574933636&toolid=10001&campid=5336728181&customid=&icep_uq=%s&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg",
    "ec": "http://www.ecosia.org/search?q=%s",
    "ed": "https://encyclopediadramatica.rs/index.php?title=Special%3ASearch&search=%s&go=Go",
    "e": "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5574933636&toolid=10001&campid=5336728181&customid=&icep_uq=%s&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg",
    "ee": "https://duckduckgo.com/?q=site%3Ahttp%3A%2F%2Fellislab.com%2Fforums%2F+%s",
    "eg": "http://duckduckgo.com/?q=%s+site:epguides.com",
    "eh": "https://www.english-heritage.org.uk/search?searchTerm=%s",
    "ei": "https://www.ecosia.org/images?q=%s",
    "ej": "http://www.tanoshiijapanese.com/dictionary/index.cfm?j=&e=%s&search=Search+%3E",
    "ek": "http://www.elektronik-kompendium.de/service/suchen/index.htm?domains=www.elektronik-kompendium.de&sitesearch=www.elektronik-kompendium.de&q=%s&sa=Suchen&client=pub-7453653573550802&forid=1&channel=3122011476&ie=ISO-8859-1&oe=ISO-8859-1&flav=0000&sig=XvZoofyEi29r3eL9&cof=GALT%3A%23008000%3BGL%3A1%3BDIV%3A%23FFFFFF%3BVLC%3A663399%3BAH%3Acenter%3BBGC%3AFFFFFF%3BLBGC%3A336699%3BALC%3A0000FF%3BLC%3A0000FF%3BT%3A000000%3BGFNT%3A0000FF%3BGIMP%3A0000FF%3BFORID%3A11&hl=de",
    "em": "http://motors.shop.ebay.com/eBay-Motors-/6000/i.html?_nkw=%s&_trksid=p2050885.m570.l1313&_rdc=1",
    "en": "http://english.stackexchange.com/search?q=%s",
    "eo": "http://www.etymonline.com/index.php?search=%s",
    "ep": "https://everipedia.org/wiki/%s",
    "er": "https://www.erowid.org/search.php?q=%s",
    "es": "https://duckduckgo.com/?q=%s&kl=xl-es&kad=es_ES&ia=about",
    "et": "http://www.eltiempo.es/buscar?q=%s",
    "ev": "https://cse.google.com/cse?cx=008464549922976904202:3wy4ipwvlno&q=%s&oq={{{s}}}&gs_l=partner-generic.3...27208.27522.3.27758.3.3.0.0.0.0.67.174.3.3.0.gsnos%2Cn%3D13...0.1844j1376214j6j1...1.34.partner-generic..3.2.102.qiNHoIwD47w",
    "ew": "https://duckduckgo.com/?q=site%3Aew.com+%s",
    "ex": "https://examine.com/search/?q=%s",
    "f1": "http://www.f1zone.net/news/index.php?s=%s",
    "f3": "http://www.france3.fr/recherche?s=%s",
    "f6": "https://fordsix.com/search.php?keywords=%s",
    "fa": "http://www.filmaffinity.com/es/search.php?stext=%s&stype=all",
    "fb": "https://www.facebook.com/search.php/?q=%s",
    "fc": "https://duckduckgo.com/?q=site%3A+freecadweb.org+%s",
    "fd": "http://freedictionary.org/?Query=%s&button=Search",
    "ff": "http://www.fanfiction.net/search.php?type=story&keywords=%s&match=title&sort=0&genreid=0&subgenreid=0&characterid=0&subcharacterid=0&words=0&ready=1&categoryid=0",
    "f": "http://www.flickr.com/search/?q=%s",
    "'f": "https://www.fransktlexikon.se/%s",
    "fg": "http://www.fangraphs.com/players.aspx?lastname=%s",
    "fh": "http://filehippo.com/search?q=%s",
    "fi": "http://www.finanzen.net/suchergebnis.asp?strSuchString=%s",
    "fj": "http://funnyjunk.com/search/?q=%s",
    "fk": "http://www.flipkart.com/search?q=%s ",
    "fl": "http://www.google.com/search?btnI&q=%s",
    "fm": "http://filmaster.com/search/?q=%s",
    "fn": "https://www.foodnetwork.com/search/%s-",
    "fo": "http://file.org/extension/%s ",
    "fp": "http://www.fanpop.com/search?query=%s",
    "fr": "http://www.larousse.fr/dictionnaires/francais/%s",
    "fs": "https://factualsearch.news/#/&gsc.q=%s ",
    "ft": "https://www.ft.com/search?q=%s",
    "fv": "http://finviz.com/quote.ashx?t=%s",
    "fw": "http://www.forgottenweapons.com/?s=%s",
    "fz": "https://duckduckgo.com/?q=site%3Afz.se+%s",
    "ga": "http://www.google.com.au/search?q=%s",
    "gb": "http://books.google.com/books?q=%s&btnG=Search+Books",
    "gc": "https://contacts.google.com/search/%s",
    "gd": "https://docs.google.com/document/u/0/?q=%s",
    "ge": "https://google.com/#q=%s",
    "gf": "http://finance.google.com/?q=%s&sa=N&tab=fe",
    "gg": "http://groups.google.com/groups/search?q=%s&qt_s=Search+Groups",
    "g": "https://www.google.com/search?q=%s",
    "g+": "https://plus.google.com/u/0/s/%s ",
    "gh": "https://github.com/search?utf8=%E2%9C%93&q=%s",
    "gi": "https://google.com/search?tbm=isch&q=%s&tbs=imgo:1",
    "gj": "http://www.google.co.jp/search?q=%s",
    "gk": "https://www.gamekult.com/rechercher-jeu.html?q=%s",
    "gl": "https://www.opengl.org/search/?cx=017055583490642512057%3Ahwpumfa180i&cof=FORID%3A9&q=%s",
    "gm": "https://google.com/maps/place/%s",
    "gn": "https://news.google.com/news/search/section/q/%s",
    "go": "https://mail.google.com/mail/u/0/#search/%s",
    "gp": "https://play.google.com/store/search?q=%s",
    "gq": "http://www.gq.com/search?qt=dismax&sort=score+desc&query=%s",
    "gr": "https://www.goodreads.com/search?q=%s",
    "gs": "http://www.google.com/products?q=%s&sa=N&tab=pf",
    "gt": "https://translate.google.com/#auto/en/%s",
    "gu": "https://duckduckgo.com/?q=site%3Awww.theguardian.com+%s",
    "gv": "https://www.google.com/search?tbm=vid&q=%s",
    "gw": "https://wiki.gentoo.org/index.php?title=Special%3ASearch&search=%s&go=Go",
    "gy": "https://google.com/search?q=%s &tbs=qdr:y",
    "gz": "http://www.geekzone.fr/?s=%s",
    "h2": "http://www.h2olimpo.com/buscar?controller=search&orderby=position&orderway=desc&search_query=%s&submit_search=",
    "hb": "https://www.humblebundle.com/store/search?search=%s",
    "hc": "http://www.holidaycheck.de/schnellsuche.php?q=%s",
    "hd": "http://hudoc.echr.coe.int/eng#{%22fulltext%22:%22%s%22,%22documentcollectionid2%22:%22GRANDCHAMBER%22,%22CHAMBER%22}",
    "hg": "https://www.mercurial-scm.org/wiki/Mercurial?action=fullsearch&context=180&value=%s&titlesearch=Title",
    "hh": "https://www.homehardware.ca/search?query=%s",
    "h": "http://www.haskell.org/hoogle/?hoogle=%s",
    "hk": "http://hacktips.it/?s=%s",
    "hl": "http://hugelol.com/search?q=%s",
    "hm": "https://wego.here.com/search/%s?",
    "hn": "https://hn.algolia.com/?q=%s",
    "ho": "http://www.haskell.org/hoogle/?hoogle=%s",
    "hp": "http://search.hp.com/query.html?lang=en&submit.x=0&submit.y=0&qt=%s&la=en&cc=us",
    "hs": "http://honyakustar.com/en/%s ",
    "ht": "https://hooktube.com/results?search_query=%s",
    "hu": "https://healthunlocked.com/search/%s",
    "hv": "http://www.hinnavaatlus.ee/search/?Type=products&Query=%s",
    "hw": "http://halo.umbc.edu/cgi-bin/haloweb/nrc1.pl?display=json&operation=search&keyword=%s",
    "hx": "https://hex.pm/packages?search=%s&sort=downloads",
    "hy": "https://via.hypothes.is/%s",
    "i3": "https://www.i3-technologies.com/en/resources/knowledge-base/?q=%s",
    "ia": "https://archive.org/search.php?query=%s",
    "ib": "https://www.indiebound.org/search/book?keys=%s",
    "id": "http://www.idealo.de/preisvergleich/MainSearchProductCategory.html?q=%s",
    "i": "https://duckduckgo.com/?q=%s&ia=images&iax=images",
    "ie": "https://duckduckgo.com/?q=site%3Aie+%s",
    "ig": "https://www.instagram.com/explore/tags/%s/",
    "il": "https://duckduckgo.com/?q=%s&ia=images&iax=images&iaf=size%3Aimagesize-large",
    "in": "https://invidio.us/search?q=%s",
    "ip": "http://whatismyipaddress.com/ip/%s",
    "is": "http://ilmainensanakirja.fi/sanakirja/%s?",
    "it": "https://duckduckgo.com/?q=%s&kl=it-it",
    "iv": "http://www.italian-verbs.com/italian-verbs/conjugation.php?verbo=%s",
    "iw": "http://instantwatcher.com/search?content_type=1+2&source=1+2+3&q=%s",
    "j\u00e1": "http://ja.is/?q=%s",
    "ja": "http://www.j-archive.com/search.php?search=%s",
    "jb": "http://www.jupiterbroadcasting.com/?s=%s",
    "jd": "http://search.jd.com/Search?keyword=%s&enc=utf-8",
    "je": "http://www.tanoshiijapanese.com/dictionary/index.cfm?j=%s&e=&search=Search+%3E",
    "ji": "https://jisho.org/search/%s",
    "j": "https://jet.com/search?term=%s",
    "jj": "http://jinja.pocoo.org/docs/2.10/search/?q=%s",
    "jl": "http://www.johnlewis.com/Search/Search.aspx?SearchTerm=%s",
    "jm": "http://joemonster.org/search.php?q=%s",
    "jn": "https://www.jellynote.com/en/search?q=%s",
    "jo": "https://www.jotrin.com/product/list?keyword=%s",
    "jp": "http://www.jetpens.com/search?q=%s",
    "jq": "http://api.jquery.com/?ns0=1&s=%s",
    "jr": "http://joyreactor.cc/search?q=%s",
    "js": "https://developer.mozilla.org/en-US/search?topic=api&topic=js&q=%s",
    "jv": "http://www.jeuxvideo.com/recherche.php?q=%s",
    "jw": "http://www.jw.org/en/search/?q=%s",
    "ka": "https://www.khanacademy.org/search?page_search_query=%s",
    "kb": "http://duckduckgo.com/?q=site%3Akeybase.io+%s",
    "kd": "http://kanjidamage.com/kanji/search?utf8=%E2%9C%93&q=%s",
    "kf": "https://kasperfred.com/posts/?q=%s",
    "kg": "http://kg-portal.ru/?search&s_str= %s",
    "kh": "https://hub.kubeapps.com/charts?q=%s",
    "kj": "http://www.biblestudytools.com/search/?q=%s&s=Bibles&t=kjv",
    "kk": "https://kubekings.com/buscar?controller=search&orderby=position&orderway=desc&search_query=%s&submit_search=",
    "k": "https://www.konsolentreff.de/search/1/?q=%s",
    "kn": "https://knoema.com/search?query=%s",
    "kp": "https://www.kupujemprodajem.com/search.php?action=list&data%5Bad_kind%5D=&data%5Bad_type%5D=&data%5Bfollow%5D=&data%5Bad_kind_type%5D=&data%5Btip_oglasa%5D=&data%5Bcategory_id%5D=&data%5Bgroup_id%5D=&data%5Blocation_id%5D=&data%5Blocation_radius%5D=&data%5Bhas_photo%5D=&data%5Bcondition%5D=&data%5Bperiod%5D=&data%5Border%5D=&data%5Bcar_model%5D=&data%5Bvehicle_power_min%5D=&data%5Bvehicle_power_max%5D=&data%5Bvehicle_cc_min%5D=&data%5Bvehicle_cc_max%5D=&data%5Bvehicle_km_min%5D=&data%5Bvehicle_km_max%5D=&data%5Bvehicle_make_year_min%5D=&data%5Bvehicle_make_year_max%5D=&data%5Bcar_body_type%5D=&data%5Bcar_fuel_type%5D=&data%5Bcar_doors%5D=&data%5Bcar_gearbox%5D=&data%5Bvehicle_aircondition%5D=&data%5Bvehicle_drive%5D=&data%5Bprice_from%5D=&data%5Bprice_to%5D=&dummy=name&data%5Bkeywords%5D=%s &=&=&=&=&=&=&return_url=aW5kZXgucGhw",
    "kr": "https://www.kroger.com/search?query=%s",
    "ks": "http://www.kickstarter.com/projects/search?utf8=\u2713&term=%s+",
    "kt": "http://www.kicktraq.com/search/?find=%s",
    "l1": "https://level-1.fr/?s=%s",
    "la": "https://de.langenscheidt.com/deutsch-englisch/search?term=%s",
    "lb": "https://letterboxd.com/search/%s/",
    "lc": "https://laracasts.com/search?q=%s",
    "ld": "http://www.ldoceonline.com/search/?q=%s",
    "le": "https://le.ac.uk/search?q=%s",
    "lf": "http://www.lesfrontaliers.lu/search?text=%s",
    "lh": "http://lifehacker.com/search?q=%s",
    "li": "https://www.linkedin.com/search/results/index/?keywords=%s",
    "lj": "http://duckduckgo.com/?q=site%3Alivejournal.com+%s ",
    "lk": "http://www.lolking.net/search?name=%s",
    "ll": "http://www.liveleak.com/browse?q=%s",
    "lm": "http://www.livemixtapes.com/main.php?artist=%s",
    "ln": "http://lenewbie.com/?s=%s",
    "lp": "https://launchpad.net/+search?field.text=%s",
    "lq": "https://forum.linuxquimper.org/search?q=%s",
    "ls": "http://littlesis.org/search?q=%s",
    "lt": "https://www.librarything.com/search.php?searchtype=work&search=%s",
    "lu": "https://www.liberty.edu/search/?q=%s",
    "lv": "http://www.livermore.lib.ca.us/search/a?searchtype=X&SORT=D&searchscope=7&searcharg=%s",
    "lw": "http://lesswrong.com/search/results?cx=015839050583929870010%3A-802ptn4igi&cof=FORID%3A11&ie=UTF-8&sa=Search&siteurl=lesswrong.com%2F&q=%s",
    "lx": "http://www.lexicanum.com/search.php?q=%s&x=0&y=0",
    "m1": "https://www.motor1.com/search/?q=%s",
    "ma": "http://en.memory-alpha.org/wiki/Special:Search?search=%s&fulltext=Search",
    "mb": "http://musicbrainz.org/search/textsearch.html?type=artist&query=%s&handlearguments=1",
    "mc": "http://www.metacritic.com/search/all/%s/results",
    "md": "https://docs.microsoft.com/en-us/search/index?search=%s",
    "me": "http://masseffect.wikia.com/wiki/Special:Search?search=%s&fulltext=Search",
    "mf": "https://morguefile.com/search/morguefile/1/%s/pop",
    "m": "http://maps.google.com/maps?q=%s",
    "mh": "http://monsterhunter.wikia.com/wiki/index.php?search=%s",
    "mi": "http://www.myinstants.com/search/?name=%s",
    "mk": "http://mechanicalkeyboards.com/search.php?switch_id=ALL&size=ALL&keyword=%s ",
    "ml": "https://google.com/maps/search/%s?force=canvas",
    "mm": "http://www.macmillandictionary.com/us/search/british/direct/?q=%s",
    "mn": "http://www.medicinanet.com.br/pesquisas/%s.htm",
    "mo": "http://mathoverflow.net/search?q=%s",
    "mp": "http://www.menupages.com/restaurants/text/%s/all-areas/all-neighborhoods/all-cuisines/",
    "mq": "http://www.mapquest.com/?q=%s",
    "mr": "http://www.macrumors.com/search?s=%s",
    "ms": "http://search.microsoft.com/results.aspx?mkt=en-US&form=MSHOME&setlang=en-US&q=%s",
    "mt": "http://www.multitran.ru/c/m.exe?s=%s ",
    "mu": "http://macupdate.com/find/mac/%s",
    "mv": "http://www.myvideo.de/Videos_A-Z?searchWord=%s",
    "mw": "http://www.merriam-webster.com/dictionary/%s",
    "mx": "http://mxtoolbox.com/SuperTool.aspx?action=mx%3a%s&run=networktools",
    "mz": "https://www.mittelbayerische.de/suche/?scope=20000&type=articles%2Cgalleries%2Cvideos&interval=month&searchterm=%s",
    "na": "https://search.naver.com/search.naver?query=%s",
    "\u3134": "https://search.naver.com/search.naver?query=%s",
    "nb": "http://www.nb.no/nbsok/search?page=0&menuOpen=false&instant=true&action=search&currentHit=-1&searchString=%s",
    "nc": "https://www.namecheap.com/domains/registration/results.aspx?domain=%s ",
    "nd": "https://onesearch.library.nd.edu/primo-explore/search?query=any,contains,%s&tab=onesearch&search_scope=malc_blended&vid=NDU&lang=en_US&offset=0",
    "n": "https://duckduckgo.com/?q=%s&iar=news&ia=news",
    "ne": "http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&DEPA=0&Description=%s",
    "nf": "https://www.netflix.com/search?q=%s",
    "ng": "https://angular.io/api?query=%s",
    "nh": "https://nethackwiki.com/mediawiki/index.php?search=%s",
    "ni": "http://search.ni.com/nisearch/app/main/p/bot/no/ap/global/lang/en/pg/1/q/%s/",
    "nk": "https://norgeskart.no/#!?project=seeiendom&layers=1002,1015&zoom=4&lat=7197864.00&lon=396722.00&sok=%s",
    "nl": "http://ncatlab.org/nlab/search?query=%s",
    "nm": "https://www.nexusmods.com/search/?gsearch=%s&gsearchtype=mods",
    "nn": "https://www.naturalnews.com/SearchResults.asp?query=%s&pr=NN",
    "np": "http://thenounproject.com/search/?q=%s",
    "ns": "http://duckduckgo.com/?q=!safeoff+%s",
	"wno": "https://no.wikipedia.org/w/index.php?search=%s",
    "nt": "https://newstral.com/search/articles?&q=%s",
    "nu": "http://www.nu.nl/zoeken/?q=%s ",
    "nv": "http://m.search.naver.com/search.naver?query=%s):",
    "nw": "http://ninjawords.com/%s",
    "nx": "http://networkx.lanl.gov/search.html?q=%s&check_keywords=yes&area=default",
    "o2": "https://www.o2.co.uk/shop/%s",
    "ob": "https://openbuilds.com/search/49203883/?q=%s",
    "oc": "https://openclassrooms.com/courses?q=%s",
    "od": "http://oxforddictionaries.com/definition/english/%s?q={{{s}}}",
    "\u00f5": "http://www.eki.ee/dict/qs/index.cgi?Q=%s",
    "of": "https://duckduckgo.com/?q=%s+site%3Ahttp%3A%2F%2Fforum.openframeworks.cc",
    "og": "https://duckduckgo.com/?q=%s+site%3Aomniglot.com",
    "oh": "https://www.openhub.net/p?q=%s",
    "oi": "http://oxfordindex.oup.com/search?q=%s",
    "ol": "http://search.oregonlive.com/%s",
    "on": "https://www.ontario.ca/search/search-results?query=%s",
    "o": "http://onelook.com/?w=%s&ls=a",
    "oo": "https://www.otto-office.com/de/app/search/index?queryquery=%s",
    "or": "https://or.justice.cz/ias/ui/rejstrik-$firma?jenPlatne=PLATNE&nazev=%s&polozek=50&typHledani=STARTS_WITH",
    "\u00f5s": "http://www.eki.ee/dict/qs/index.cgi?Q=%s",
    "os": "http://software.opensuse.org/search?utf8=\u2713&q=%s&search_devel=false&search_unsupported=false&baseproject=openSUSE:13.1",
    "ou": "http://www.ou.edu/content/web/search.html?q=%s",
    "ov": "http://stackoverflow.com/search?q=%s",
    "ow": "https://openwhyd.org/search?q=%s",
    "ox": "https://www.lexico.com/search?utf8=%E2%9C%93&filter=dictionary&dictionary=en&query=%s",
    "oz": "http://oz.by/search/?q=%s",
    "pa": "https://www.paginasamarillas.es/search/all-ac/all-ma/all-pr/all-is/all-ci/all-ba/all-pu/all-nc/1?what=%s",
    "pb": "http://pinboard.in/search/?query=%s&mine=Search+Mine",
    "pc": "http://www.presidentschoice.ca/en_CA/search-page.query@%s.html",
    "pd": "http://folkets-lexikon.csc.kth.se/folkets/folkets.en.html#lookup&%s&0",
    "pe": "https://www.infopedia.pt/dicionarios/pesquisa/%s",
    "pf": "http://www.printfriendly.com/print/?source=site&url=%s",
    "pg": "https://www.gutenberg.org/ebooks/search/?query=%s",
    "ph": "https://www.producthunt.com/search?q=%s",
    "pi": "http://www.philly.com/philly/search/?search=y&adv=y&searchKeywords=%s&minscore=50&pagesize=20&sites=philly&fields=full&sections=5&queryType=all",
    "pj": "https://www.prisjakt.nu/search?search=%s",
    "pk": "https://peekier.com/#!%s",
    "pl": "http://publiclab.org/search/%s",
    "pm": "https://www.ncbi.nlm.nih.gov/pubmed/?term=%s",
    "pn": "https://primenow.amazon.com/search?k=%s",
    "po": "https://prensaobrera.com/buscar?q=%s",
    "p": "https://www.pinterest.com/search/pins/?q=%s",
    "pp": "http://passapalavra.info/?s=%s",
    "pr": "http://ar.prvademecum.com/?s=%s",
    "ps": "https://www.playstation.com/search-results/?q=%s",
    "pt": "https://www.powerthesaurus.org/%s",
    "pu": "https://www.pulseuniform.com/search.asp?q=%s",
    "pv": "https://www.primevideo.com/region/eu/search/ref=dv_web_nav_search?phrase=%s&ie=UTF8",
    "pw": "http://www.pricewatch.com/search?q=%s ",
    "px": "http://pixabay.com/en/photos/?q=%s",
    "py": "https://docs.python.org/3/search.html?q=%s",
    "qb": "https://www.quimbee.com/search?q=%s",
    "qc": "https://www.qconcursos.com/busca?q=%s",
    "qm": "https://www.qwant.com/music/search?q=%s",
    "qp": "https://www.quip.com/search?q=%s",
    "q": "https://www.quora.com/search?q=%s",
    "qr": "https://api.qrserver.com/v1/create-qr-code/?qzone=1&data=%s",
    "qs": "https://help.qlik.com/en-US/search/?q=%s",
    "qt": "https://doc.qt.io/qt-5/search-results.html?q=%s",
    "qw": "http://www.qwant.com/?q=%s",
    "qz": "http://qz.com/search/%s",
    "r7": "http://www.rapid7.com/db/search?utf8=%E2%9C%93&q=%s &t=a",
    "ra": "http://www.residentadvisor.net/search.aspx?searchstr=%s",
    "rb": "https://rubydocs.org/d/ruby-latest/?q=%s",
    "rc": "https://www.readerscave.com/?s=%s",
    "rf": "http://www.reasonablefaith.org/search/results?q=%s",
    "rg": "http://rapgenius.com/search?q=%s",
    "rh": "https://robinhood.com/stocks/%s",
    "rj": "https://www.radiojavan.com/search?query=%s",
    "rk": "http://www.robokart.com/index.php?route=product/search&search=%s",
    "rm": "http://www.gurusrom.net/search/term=%s",
    "rn": "http://india.recruit.net/search.html?query=%s&location=delhi",
    "ro": "https://www.admin.ch/opc/search/?text=%s&lang=fr&language%5B%5D=fr&product%5B%5D=ClassifiedCompilation",
    "rp": "http://www.raspberrypi.org/phpBB3/search.php?keywords=%s",
    "r": "https://www.reddit.com/search?q=%s",
    "rr": "http://reprap.org/mediawiki/index.php?search=%s",
    "rs": "https://runescape.wiki/?search=%s",
    "rt": "https://www.rottentomatoes.com/search/?search=%s",
    "ru": "http://www.redusers.com/noticias/?s=%s",
    "rv": "https://www.real.video/search?query=%s",
    "rw": "http://rationalwiki.org/w/index.php?search=%s",
    "rz": "http://www.rhymezone.com/r/rhyme.cgi?Word=%s&typeofrhyme=perfect&org1=syl&org2=l&org3=y",
    "s2": "https://www.semanticscholar.org/search?q=%s",
    "s6": "http://society6.com/search/?q=%s",
    "s9": "https://sanctum9.wordpress.com/?s=%s",
    "sa": "http://www.scientificamerican.com/search/?q=%s&x=-783&y=-180 ",
    "sb": "http://www.swagbucks.com/?t=w&p=1&b=0&f=0&sef=1&q=%s",
    "sc": "https://soundcloud.com/search?q=%s",
    "sd": "https://slickdeals.net/newsearch.php?q=%s&searcharea=deals&searchin=first",
    "se": "http://stackexchange.com/search?q=%s",
    "sf": "http://serverfault.com/search?q=%s",
    "sg": "https://sourcegraph.com/search?q=%s",
    "si": "https://www.si.com/search?q=%s",
    "sj": "https://www.sitejabber.com/search?q=%s",
    "sk": "http://www.songkick.com/search?query=%s",
    "/.": "http://slashdot.org/index2.pl?fhfilter=%s",
    "./": "http://slashdot.org/index2.pl?fhfilter=%s",
    "sl": "http://www.setlist.fm/search?query=%s",
    "sm": "http://www.smashingmagazine.com/search-results/?q=%s&cx=partner-pub-6779860845561969%3A5884617103&cof=FORID%3A10&ie=UTF-8",
    "sn": "http://soylentnews.org/search.pl?query=%s",
    "so": "http://stackoverflow.com/search?q=%s",
    "sp": "https://startpage.com/do/metasearch.pl?query=%s",
    "sr": "http://reddit.com/r/%s",
    "ss": "https://surrey-primotc.hosted.exlibrisgroup.com/primo-explore/search?vl(freeText0)=%s&fn=search&vid=44SUR_VU1&tab=default_tab&query=any,contains,{{{s}}}&search_scope=default_scope",
    "s": "http://startpage.com/do/metasearch.pl?query=%s",
    "$": "https://stockflare.com/#stocks/$%s ",
    "st": "http://stocktwits.com/search?q=%s",
    "su": "http://superuser.com/search?q=%s",
    "sv": "https://voat.co/v/%s",
    "sw": "https://simple.wikipedia.org/wiki/Special:Search?search=%s&go=Go",
    "sx": "http://stackexchange.com/search?q=%s ",
    "sy": "http://words.bighugelabs.com/%s",
    "sz": "http://suche.sueddeutsche.de/news?search=%s",
    "ta": "http://www.tripadvisor.com/Search?q=%s ",
    "tb": "http://www.olx.co.id/halaman/mencari/%s/search",
    "tc": "http://techcrunch.com/search/%s",
    "td": "http://www.timeanddate.com/search/results.html?query=%s",
    "te": "http://www.treccani.it/enciclopedia/tag/%s/",
    "tf": "https://www.tensorflow.org/s/results/?q=%s",
    "tg": "http://www.thinkgeek.com/brain/whereisit.cgi?t=%s",
    "ti": "http://tunein.com/search/?query=%s",
    "tj": "https://www.tacojohns.com/?s=%s",
    "tl": "http://www.teamliquid.net/forum/search.php?q=%s",
    "tm": "http://www.trademe.co.nz/Browse/SearchResults.aspx?searchString=%s",
    "tp": "https://thesaurus.plus/search?q=%s",
    "tr": "http://translate.google.com/#auto/en/%s",
    "ts": "http://www.turbosquid.com/Search/Index.cfm?keyword=%s",
    "t+": "http://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-fra.html?lang=fra&i=&index=alt&__index=alt&srchtxt=%s&comencsrch.x=0&comencsrch.y=0",
    "t": "http://www.thesaurus.com/browse/%s",
    "tt": "https://www.texastribune.org/search/?q=%s",
    "tu": "https://tu-dresden.de/@@search?SearchableText=%s",
    "tv": "http://www.tv.com/search?q= %s",
    "@": "https://twitter.com/%s",
    "tw": "https://twitter.com/search?q=%s",
    "tx": "http://search2.tv-tokyo.co.jp/pc/?enc=UTF-8&q=%s",
    "ty": "https://www.youtube.com/results?search_query=%s",
    "tz": "http://www.timeanddate.com/worldclock/results.html?query=%s",
    "ub": "https://gu-se-primo.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,%s&tab=default_tab&search_scope=default_scope&vid=46GUB_VU1&lang=sv_SE&offset=0",
    "uc": "https://catalog.lib.uchicago.edu/vufind/Search/Results?lookfor=%s&type=AllFields",
    "ud": "https://www.urbandictionary.com/define.php?term=%s",
    "ug": "https://www.ultimate-guitar.com/search.php?search_type=title&value=%s",
    "uh": "https://www.uhasselt.be/google-search?q=%s",
    "ul": "https://www.ulule.com/discover/?q=%s",
    "un": "http://search.un.org/search?ie=utf8&site=un_org&output=xml_no_dtd&client=UN_Website_en&num=10&lr=lang_en&proxystylesheet=UN_Website_en&oe=utf8&q=%s&Submit=Go",
    "up": "http://packages.ubuntu.com/search?keywords=%s&searchon=names",
    "uq": "http://wiki.uqm.stack.nl/script/index.php?search=%s&go=Go&title=Special%3ASearch",
    "ur": "http://suche.uni-regensburg.de/index.php?q=%s",
    "us": "https://userstyles.org/styles/browse?search_terms=%s",
    "ut": "https://www.utexas.edu/search/results?query=%s",
    "u": "http://www.urbandictionary.com/define.php?term=%s",
    "uu": "https://duckduckgo.com/?q=site%3Aubuntuusers.de+%s",
    "uw": "https://www.ssjoy.org/dho/?vid=&mid=home&act=IS&is_target=all&is_keyword=%s",
    "ux": "http://ux.stackexchange.com/search?q=%s",
    "va": "http://vimawesome.com/?q=%s",
    "vb": "http://vedabase.com/en/search/site/%s",
    "vc": "https://www.vouchercodes.co.uk/search/?q=%s",
    "v": "https://duckduckgo.com/?q=%s&ia=videos&iax=videos",
    "ve": "https://videoeta.com/search?utf8=%E2%9C%93&keywords=%s",
    "vf": "http://www.verbformen.de/konjugation/?i=%s",
    "vg": "https://google.com/search?hl=en&q=%s&tbs=li:1",
    "vj": "http://vjphotos.net/?s=%s",
    "vk": "http://vk.com/search?cq=%s&csection=auto",
    "vo": "https://eo.wikipedia.org/w/index.php?search=%s",
    "vp": "http://videogames.pricecharting.com/search?q=%s&type=videogames&go=Go",
    "vs": "http://www.vividseats.com/Search.action?searchTerm=%s",
    "vt": "http://www.vulgumtechus.com/index.php?title=Sp\u00e9cial:Recherche&search=%s",
    "vw": "https://wiki.voidlinux.org/index.php?search=%s&title=Special%3ASearch&go=Go",
    "vy": "https://www.vajehyab.com/?q=%s",
    "w0": "https://www.wikizero.com/search.php?s=%s&lang=en",
    "w2": "https://en.wiki2.org/w/index.php?search=%s",
    "w3": "/?q=%s+site:w3.org",
    "wa": "https://www.wolframalpha.com/input/?i=%s",
    "wb": "http://en.wikibooks.org/wiki/Special:Search?search=%s",
    "wc": "http://www.weather.com/search/enhancedlocalsearch?where=%s&loctypes=1/5/9/11/13/19/",
    "wd": "https://www.wikidata.org/w/index.php?search=%s",
    "we": "http://en.wikipedia.org/wiki/%s",
    "wf": "https://fr.wikipedia.org/wiki/Special:Search?search=%s&go=Go",
    "wg": "https://www.wunderground.com/cgi-bin/findweather/getForecast?query=%s",
    "wh": "http://www.wikihow.com/wikiHowTo?search=%s",
    "wi": "https://en.wikipedia.org/wiki/Special:Search?search=%s&go=Go",
    "wj": "https://ja.wikipedia.org/wiki/%s",
    "wk": "https://en.wikipedia.org/w/index.php?search=%s&title=Special%3ASearch&go=Go",
    "wl": "https://search.wikileaks.org/?q=%s",
    "wm": "http://en.m.wikipedia.org/wiki?search=%s",
    "wn": "https://en.wikinews.org/wiki/Special:Search?search=%s",
    "wo": "http://www.wetteronline.de/wetter/%s",
    "wp": "http://wordpress.org/search/%s",
    "wq": "https://en.wikiquote.org/w/index.php?search=%s&title=Special%3ASearch",
    "wr": "http://www.wordreference.com/definition/%s",
    "ws": "https://en.wikisource.org/wiki/Special:Search?search=%s&go=Go",
    "wt": "https://en.wiktionary.org/w/index.php?search=%s&title=Special%3ASearch&go=Go",
    "wu": "https://www.wunderground.com/cgi-bin/findweather/getForecast?query=%s",
    "wv": "https://en.wikivoyage.org/w/index.php?search=%s",
    "ww": "https://www.wikiwand.com/en/%s",
    "w": "https://en.wikipedia.org/wiki/Special:Search?search=%s",
    "wy": "http://www.wykop.pl/szukaj/%s",
    "wz": "https://www.warpzone.ms/?s=%s ",
    "xe": "https://xe.com/currency/%s",
    "xf": "https://forum.xojo.com/conversations/all?search=%s",
    "xl": "http://www.xtend-life.com/search-results?cx=005442268687610389394%3a4wscy8mawc0&cof=FORID%3a10&q=%s",
    "xt": "https://xtupleuniversity.xtuple.com/search/node/%s",
    "xu": "https://www.xavier.edu/search/?q=%s",
    "y8": "http://www.y8.com/search?utf8=%E2%9C%93&kind=game&q=%s",
    "ya": "https://yandex.ru/search/?text=%s",
    "yc": "https://hn.algolia.com/?query=%s",
    "yd": "http://www.yourdictionary.com/search/?ydQ=%s",
    "yf": "http://finance.yahoo.com/q?s=%s",
    "yg": "https://www.yeastgenome.org/search?q=%s",
    "yh": "https://yandex.com.tr/harita/?text=%s",
    "yi": "https://images.search.yahoo.com/search/images?p=%s",
    "yj": "https://search.yahoo.co.jp/search?p=%s",
    "yn": "http://yubnub.org/parser/parse?command=%s ",
    "yo": "http://yochicago.com/?s=%s",
    "yp": "https://www.yellowpages.com/search?search_terms=%s",
    "yr": "http://www.yr.no/soek/soek.aspx?sted=%s",
    "ys": "https://slovari.yandex.ru/%s",
    "yt": "https://www.youtube.com/results?search_query=%s",
    "yu": "https://hooktube.com/results?search_query=%s",
    "yv": "https://video.search.yahoo.com/search/video?p=%s",
    "yw": "https://duckduckgo.com/?q=site%3Aweather.yahoo.com+%s",
    "y": "http://search.yahoo.com/search?p=%s",
    "yz": "http://youzeek.com/?lng=RU#xPAGE_V3-Artist_%3Flng%3DRU%26Artist%3D%s%26page%3DGeneral",
    "zd": "https://www.zeldadungeon.net/?s=%s",
    "zf": "https://duckduckgo.com/?q=%s+site:framework.zend.com",
    "zh": "https://www.zerohedge.com/search-content?search_api_fulltext=%s",
    "zu": "http://www.zeldauniverse.net/?s=%s",
    "z": "https://www.zalando.de/katalog/?q=%s",
    "zw": "https://zelda.gamepedia.com/index.php?search=%s",
    "zz": "http://www.zerozero.pt/search.php?op=all&inputString=%s",
    "\u0648": "https://ar.wikipedia.org/wiki/Special:Search?search=%s",
    "\u05d2": "https://www.google.co.il/%s",
    "\u03b3": "https://www.google.gr/?gws_rd=ssl#q=%s",
    "\u03c5\u03c4": "https://www.youtube.com/results?search_query=%s",
    "\u0432": "https://uk.m.wikipedia.org/wiki/%s",
    "\u0432\u043d": "https://ru.wikinews.org/wiki/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%9F%D0%BE%D0%B8%D1%81%D0%BA?search=%s",
    "\u0432\u0441": "https://ru.wiktionary.org/w/index.php?search=%s&ns0=1",
    "\u0433": "https://google.com/search?hl=ru&q=%s",
    "\u0433\u043a": "https://www.google.ru/search?q=%s&tbm=isch",
    "\u043b": "http://www.labirint.ru/search/%s",
    "\u043f": "https://www.google.com/search?q=%s",
    "\u043f\u0448": "https://www.google.ru/search?tbm=isch&q=%s",
    "\u0446": "https://ru.wikipedia.org/wiki/Special:Search?search=%s",
    "\u0448": "https://ru.wikipedia.org/w/index.php?search=%s",
    "\u044f": "https://yandex.ru/yandsearch?text=%s",
    "\u044f\u043a": "https://yandex.ru/images/search?text=%s",
    "\u044f\u043c": "https://yandex.ru/maps/?text=%s"
};
	var engin=ss.substr(1);
	ret=arr[engin];
	if(!ret) {ret=arr[defaultengine];}
	return ret;
};
function make_queryURL(searchengine,stringquery){
	var ret=searchengine.replace('%s',stringquery);
	return ret;	
};

function navigate(url) {
  chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {
    chrome.tabs.update(tabs[0].id, {url: url});
  });
};

window.addEventListener('click',function(e){
  if(e.target.href!==undefined){
    chrome.tabs.create({url:e.target.href})
  }
});
